import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    NOTIFICATION_LIST: `${STATE_REDUCER_KEY}/NOTIFICATION_LIST`,
    NOTIFICATION_LIST_REQUEST: `${STATE_REDUCER_KEY}/NOTIFICATION_LIST_REQUEST`,
    NOTIFICATION_LIST_SUCCESS: `${STATE_REDUCER_KEY}/NOTIFICATION_LIST_SUCCESS`,
    NOTIFICATION_LIST_FAILURE: `${STATE_REDUCER_KEY}/NOTIFICATION_LIST_FAILURE`,

    READ_NOTIFICATION: `${STATE_REDUCER_KEY}/READ_NOTIFICATION`,
    READ_NOTIFICATION_REQUEST: `${STATE_REDUCER_KEY}/READ_NOTIFICATION_REQUEST`,
    READ_NOTIFICATION_SUCCESS: `${STATE_REDUCER_KEY}/READ_NOTIFICATION_SUCCESS`,
    READ_NOTIFICATION_FAILURE: `${STATE_REDUCER_KEY}/READ_NOTIFICATION_FAILURE`
};
export const notificationList = createAction(ACTION_TYPES.NOTIFICATION_LIST);
export const readNotification = createAction(ACTION_TYPES.READ_NOTIFICATION);
