import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {

    CREATE_COURSE: `${STATE_REDUCER_KEY}/CREATE_COURSE_DETAILS`,
    CREATE_COURSE_REQUEST: `${STATE_REDUCER_KEY}/CREATE_COURSE_DETAILS_REQUEST`,
    CREATE_COURSE_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_COURSE_DETAILS_SUCCESS`,
    CREATE_COURSE_FAILURE: `${STATE_REDUCER_KEY}/CREATE_COURSE_DETAILS_FAILURE`,

    UPDATE_USER_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS`,
    UPDATE_USER_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS_REQUEST`,
    UPDATE_USER_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS_SUCCESS`,
    UPDATE_USER_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_USER_DETAILS_FAILURE`,


    UPLOAD_THUMBNAIL_IMAGE: `${STATE_REDUCER_KEY}/UPLOAD_THUMBNAIL_IMAGE`,
    UPLOAD_THUMBNAIL_IMAGE_REQUEST: `${STATE_REDUCER_KEY}/UPLOAD_THUMBNAIL_IMAGE_REQUEST`,
    UPLOAD_THUMBNAIL_IMAGE_SUCCESS: `${STATE_REDUCER_KEY}/UPLOAD_THUMBNAIL_IMAGE_SUCCESS`,
    UPLOAD_THUMBNAIL_IMAGE_FAILURE: `${STATE_REDUCER_KEY}/UPLOAD_THUMBNAIL_IMAGE_FAILURE`,

    POST_OTP: `${STATE_REDUCER_KEY}/POST_OTP`,
    POST_OTP_REQUEST: `${STATE_REDUCER_KEY}/POST_OTP_REQUEST`,
    POST_OTP_SUCCESS: `${STATE_REDUCER_KEY}/POST_OTP_SUCCESS`,
    POST_OTP_FAILURE: `${STATE_REDUCER_KEY}/POST_OTP_FAILURE`,

    POST_RESET_PASSWORD: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD`,
    POST_RESET_PASSWORD_REQUEST: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_REQUEST`,
    POST_RESET_PASSWORD_SUCCESS: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_SUCCESS`,
    POST_RESET_PASSWORD_FAILURE: `${STATE_REDUCER_KEY}/POST_RESET_PASSWORD_FAILURE`,

    DROP_DOWN: `${STATE_REDUCER_KEY}/DROP_DOWN`,
    DROP_DOWN_REQUEST: `${STATE_REDUCER_KEY}/DROP_DOWN_REQUEST`,
    DROP_DOWN_SUCCESS: `${STATE_REDUCER_KEY}/DROP_DOWN_SUCCESS`,
    DROP_DOWN_FAILURE: `${STATE_REDUCER_KEY}/DROP_DOWN_FAILURE`,

    SENT_COMPLETE: `${STATE_REDUCER_KEY}/SENT_COMPLETE`,
    SENT_COMPLETE_REQUEST: `${STATE_REDUCER_KEY}/SENT_COMPLETE_REQUEST`,
    SENT_COMPLETE_SUCCESS: `${STATE_REDUCER_KEY}/SENT_COMPLETE_SUCCESS`,
    SENT_COMPLETE_FAILURE: `${STATE_REDUCER_KEY}/SENT_COMPLETE_FAILURE`,

    FETCH_COURSE: `${STATE_REDUCER_KEY}/FETCH_COURSE`,
    FETCH_COURSE_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COURSE_REQUEST`,
    FETCH_COURSE_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COURSE_SUCCESS`,
    FETCH_COURSE_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COURSE_FAILURE`,

    FETCH_COURSE_BY_ID: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_ID`,
    FETCH_COURSE_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_ID_REQUEST`,
    FETCH_COURSE_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_ID_SUCCESS`,
    FETCH_COURSE_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_ID_FAILURE`,

    FETCH_COURSE_BY_SLUG: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_SLUG`,
    FETCH_COURSE_BY_SLUG_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_SLUG_REQUEST`,
    FETCH_COURSE_BY_SLUG_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_SLUG_SUCCESS`,
    FETCH_COURSE_BY_SLUG_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COURSE_BY_COURSE_SLUG_FAILURE`,

    FETCH_VIDEOS_BY_SLUG: `${STATE_REDUCER_KEY}/FETCH_VIDEOS_BY_SLUG`,
    FETCH_VIDEOS_BY_SLUG_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VIDEOS_BY_SLUG_REQUEST`,
    FETCH_VIDEOS_BY_SLUG_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VIDEOS_BY_SLUG_SUCCESS`,
    FETCH_VIDEOS_BY_SLUG_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VIDEOS_BY_SLUG_FAILURE`,

    FETCH_LECTURE_BY_ID: `${STATE_REDUCER_KEY}/FETCH_LECTURE_BY_ID`,
    FETCH_LECTURE_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_LECTURE_BY_ID_REQUEST`,
    FETCH_LECTURE_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_LECTURE_BY_ID_SUCCESS`,
    FETCH_LECTURE_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_LECTURE_BY_ID_FAILURE`,

    STREAM_LECTURE: `${STATE_REDUCER_KEY}/STREAM_LECTURE`,
    STREAM_LECTURE_REQUEST: `${STATE_REDUCER_KEY}/STREAM_LECTURE_REQUEST`,
    STREAM_LECTURE_SUCCESS: `${STATE_REDUCER_KEY}/STREAM_LECTURE_SUCCESS`,
    STREAM_LECTURE_FAILURE: `${STATE_REDUCER_KEY}/STREAM_LECTURE_FAILURE`,

    DELETE_LECTURE: `${STATE_REDUCER_KEY}/DELETE_LECTURE`,
    DELETE_LECTURE_REQUEST: `${STATE_REDUCER_KEY}/DELETE_LECTURE_REQUEST`,
    DELETE_LECTURE_SUCCESS: `${STATE_REDUCER_KEY}/DELETE_LECTURE_SUCCESS`,
    DELETE_LECTURE_FAILURE: `${STATE_REDUCER_KEY}/DELETE_LECTURE_FAILURE`,


    UPLOAD_ATTACHMENTS: `${STATE_REDUCER_KEY}/UPLOAD_ATTACHMENTS`,
    UPLOAD_ATTACHMENTS_REQUEST: `${STATE_REDUCER_KEY}/UPLOAD_ATTACHMENTS_REQUEST`,
    UPLOAD_ATTACHMENTS_SUCCESS: `${STATE_REDUCER_KEY}/UPLOAD_ATTACHMENTS_SUCCESS`,
    UPLOAD_ATTACHMENTS_FAILURE: `${STATE_REDUCER_KEY}/UPLOAD_ATTACHMENTS_FAILURE`,

    FETCH_VIDEO_BY_VID: `${STATE_REDUCER_KEY}/FETCH_VIDEO_BY_VID`,
    FETCH_VIDEO_BY_VID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VIDEO_BY_VID_REQUEST`,
    FETCH_VIDEO_BY_VID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VIDEO_BY_VID_SUCCESS`,
    FETCH_VIDEO_BY_VID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VIDEO_BY_VID_FAILURE`,


    PUBLISH_COURSE: `${STATE_REDUCER_KEY}/PUBLISH_COURSE`,
    PUBLISH_COURSE_REQUEST: `${STATE_REDUCER_KEY}/PUBLISH_COURSE_REQUEST`,
    PUBLISH_COURSE_SUCCESS: `${STATE_REDUCER_KEY}/PUBLISH_COURSE_SUCCESS`,
    PUBLISH_COURSE_FAILURE: `${STATE_REDUCER_KEY}/PUBLISH_COURSE_FAILURE`,

    EDIT_COURSE: `${STATE_REDUCER_KEY}/EDIT_COURSE`,
    EDIT_COURSE_REQUEST: `${STATE_REDUCER_KEY}/EDIT_COURSE_REQUEST`,
    EDIT_COURSE_SUCCESS: `${STATE_REDUCER_KEY}/EDIT_COURSE_SUCCESS`,
    EDIT_COURSE_FAILURE: `${STATE_REDUCER_KEY}/EDIT_COURSE_FAILURE`,

    DELETE_COURSE: `${STATE_REDUCER_KEY}/DELETE_COURSE`,
    DELETE_COURSE_REQUEST: `${STATE_REDUCER_KEY}/DELETE_COURSE_REQUEST`,
    DELETE_COURSE_SUCCESS: `${STATE_REDUCER_KEY}/DELETE_COURSE_SUCCESS`,
    DELETE_COURSE_FAILURE: `${STATE_REDUCER_KEY}/EDIT_COURSE_FAILURE`

};

export const createCourse = createAction(ACTION_TYPES.CREATE_COURSE);
export const editCourse = createAction(ACTION_TYPES.EDIT_COURSE);
export const deleteCourse = createAction(ACTION_TYPES.DELETE_COURSE);

export const uploadThumbnailImage = createAction(ACTION_TYPES.UPLOAD_THUMBNAIL_IMAGE);
export const updateUserDetails = createAction(ACTION_TYPES.UPDATE_USER_DETAILS);
export const fetchDropdown = createAction(ACTION_TYPES.DROP_DOWN_FAILURE);
export const fetchCourses = createAction(ACTION_TYPES.FETCH_COURSE);
export const fetchCourseById = createAction(ACTION_TYPES.FETCH_COURSE_BY_ID);
export const fetchLectureById = createAction(ACTION_TYPES.FETCH_LECTURE_BY_ID);
export const streamLecture = createAction(ACTION_TYPES.STREAM_LECTURE);

export const sentCompleteVideo = createAction(ACTION_TYPES.SENT_COMPLETE);
export const fetchCourseBySlug = createAction(ACTION_TYPES.FETCH_COURSE_BY_SLUG);
export const deleteLectureVideo = createAction(ACTION_TYPES.DELETE_LECTURE);

export const uploadAttachments = createAction(ACTION_TYPES.UPLOAD_ATTACHMENTS);

export const fetchVideosById = createAction(ACTION_TYPES.FETCH_VIDEO_BY_VID);
export const publishCourse = createAction(ACTION_TYPES.PUBLISH_COURSE);
